"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Clapperboard, Sparkles, Loader2, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface AnimationGeneratorProps {
  topic: string;
  language: string;
}

const CARTOON_STYLES = [
  {
    id: "anime",
    label: "Anime",
    emoji: "⚔️",
    description: "Japanese animation style — expressive characters, dramatic scenes",
    color: "border-pink-500 bg-pink-500/10 text-pink-600 dark:text-pink-400",
    characters: "a determined young student character with big eyes and spiky hair",
    setting: "a mystical school floating in the clouds",
    tone: "epic and inspiring",
  },
  {
    id: "tomjerry",
    label: "Tom & Jerry",
    emoji: "🐱🐭",
    description: "Classic cartoon slapstick comedy style",
    color: "border-yellow-500 bg-yellow-500/10 text-yellow-600 dark:text-yellow-400",
    characters: "a clever mouse who loves learning and a curious cat who keeps getting surprised",
    setting: "a cozy classroom with chalkboards and cheese",
    tone: "funny and slapstick comedy",
  },
  {
    id: "dora",
    label: "Dora",
    emoji: "🗺️",
    description: "Interactive adventure style for young learners",
    color: "border-orange-500 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    characters: "Dora the Explorer and her backpack Mochila",
    setting: "a colorful jungle with interactive elements",
    tone: "interactive, encouraging, and educational",
  },
  {
    id: "doraemon",
    label: "Doraemon",
    emoji: "🤖",
    description: "Gadget-powered learning adventures",
    color: "border-blue-500 bg-blue-500/10 text-blue-600 dark:text-blue-400",
    characters: "Doraemon the robotic cat and Nobita the student",
    setting: "a futuristic room with a magical pocket full of gadgets",
    tone: "imaginative, gadget-filled, and heartwarming",
  },
  {
    id: "heidi",
    label: "Heidi",
    emoji: "⛰️",
    description: "Peaceful nature and discovery style",
    color: "border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    characters: "Heidi and her grandfather in the Swiss Alps",
    setting: "beautiful mountain meadows with goats and wildflowers",
    tone: "peaceful, warm, and full of wonder",
  },
];

export function AnimationGenerator({ topic, language }: AnimationGeneratorProps) {
  const [topicInput, setTopicInput] = useState(topic);
  const [selectedStyle, setSelectedStyle] = useState("doraemon");
  const [storyboard, setStoryboard] = useState("");
  const [loading, setLoading] = useState(false);
  const [duration, setDuration] = useState(3);

  const style = CARTOON_STYLES.find((s) => s.id === selectedStyle)!;

  const generate = async () => {
    setLoading(true);
    setStoryboard("");
    try {
      const res = await fetch("/api/backend/api/v1/chat/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Write a ${duration}-minute ${style.label} cartoon animation storyboard about: "${topicInput}".

Animation Style: ${style.label}
Characters: ${style.characters}
Setting: ${style.setting}
Tone: ${style.tone}

Format as a storyboard with numbered scenes:

SCENE 1:
[VISUAL]: What we see on screen (detailed description for animators)
[DIALOGUE]: What characters say
[ACTION]: Character movements and animations
[SOUND]: Background music and sound effects
[DURATION]: Time in seconds

Make it educational, entertaining, and true to the ${style.label} style.
Teach the topic: "${topicInput}" naturally through the story.
Language for dialogue: ${language}
Total scenes: ${duration * 4} scenes`,
          topic: topicInput,
          level: "child",
          history: [],
        }),
      });
      const data = await res.json();
      setStoryboard(data.reply);
    } catch {
      setStoryboard("Storyboard generation failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const download = () => {
    const content = `ANIMATION STORYBOARD
Style: ${style.label} ${style.emoji}
Topic: ${topicInput}
Duration: ${duration} minutes
Language: ${language}
Generated by EduSwarm

${"=".repeat(50)}

${storyboard}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${topicInput.replace(/\s+/g, "_")}_${selectedStyle}_storyboard.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="space-y-1.5">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Topic</label>
        <input value={topicInput} onChange={(e) => setTopicInput(e.target.value)}
          placeholder="e.g. The water cycle"
          className="w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30"
        />
      </div>

      {/* Cartoon style selector */}
      <div className="space-y-1.5">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Cartoon Style</label>
        <div className="space-y-2">
          {CARTOON_STYLES.map((s) => (
            <button key={s.id} onClick={() => setSelectedStyle(s.id)}
              className={`w-full flex items-center gap-3 rounded-xl border-2 p-3 text-left transition-all
                ${selectedStyle === s.id ? s.color : "border-border bg-muted/20 hover:bg-muted/40"}`}
            >
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="min-w-0">
                <p className="font-semibold text-sm">{s.label}</p>
                <p className="text-xs text-muted-foreground truncate">{s.description}</p>
              </div>
              {selectedStyle === s.id && (
                <span className="ml-auto text-xs font-bold shrink-0">✓</span>
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Duration */}
      <div className="space-y-1.5">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Duration: {duration} min
        </label>
        <input type="range" min={1} max={10} value={duration}
          onChange={(e) => setDuration(Number(e.target.value))}
          className="w-full accent-primary"
        />
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>1 min</span><span>10 min</span>
        </div>
      </div>

      <Button onClick={generate} disabled={loading || !topicInput.trim()} className="w-full gap-2">
        {loading
          ? <><Loader2 className="h-4 w-4 animate-spin" />Animating story…</>
          : <><Sparkles className="h-4 w-4" />Generate {style.label} Storyboard</>}
      </Button>

      <AnimatePresence>
        {storyboard && (
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="space-y-3">

            {/* Style badge */}
            <div className={`flex items-center gap-2 rounded-xl border-2 px-3 py-2 ${style.color}`}>
              <span className="text-xl">{style.emoji}</span>
              <div>
                <p className="text-xs font-bold">{style.label} Style</p>
                <p className="text-xs opacity-80">{style.tone}</p>
              </div>
            </div>

            {/* Storyboard preview */}
            <div className="rounded-xl border bg-muted/20 p-3 max-h-64 overflow-y-auto text-xs leading-relaxed whitespace-pre-wrap font-mono text-muted-foreground">
              {storyboard}
            </div>

            {/* External tools info */}
            <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-3 text-xs text-yellow-600 dark:text-yellow-400">
              <p className="font-semibold mb-1">🎨 To create the animation:</p>
              <ul className="space-y-0.5 list-disc list-inside text-yellow-500/80">
                <li>Animaker — drag & drop cartoon creator</li>
                <li>Powtoon — animated presentations</li>
                <li>Adobe Animate — professional 2D animation</li>
                <li>Vyond — business animation tool</li>
              </ul>
            </div>

            <Button onClick={download} className="w-full gap-2 bg-yellow-500 hover:bg-yellow-600 text-black font-semibold">
              <Download className="h-4 w-4" />
              Download Storyboard
            </Button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
