"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Presentation, Plus, Trash2, Download, Sparkles, Loader2, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Slide {
  title: string;
  bullets: string[];
  emoji: string;
}

interface PPTGeneratorProps {
  topic: string;
  language: string;
}

const EMOJIS = ["🚀", "💡", "🎯", "📚", "🌟", "🔬", "💻", "🎨", "🧠", "⚡"];

export function PPTGenerator({ topic, language }: PPTGeneratorProps) {
  const [slides, setSlides] = useState<Slide[]>([]);
  const [loading, setLoading] = useState(false);
  const [currentSlide, setCurrentSlide] = useState(0);
  const [slideCount, setSlideCount] = useState(5);
  const [previewMode, setPreviewMode] = useState(false);
  const [topicInput, setTopicInput] = useState(topic);

  const generateSlides = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/backend/api/v1/chat/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Create a ${slideCount}-slide presentation about: "${topicInput}".
Return ONLY a valid JSON array. Each slide must have:
- "title": slide title (short, max 8 words)
- "bullets": array of 3-4 bullet points (each max 12 words)
- "emoji": one relevant emoji

Example format:
[{"title":"Introduction","bullets":["Point 1","Point 2","Point 3"],"emoji":"🚀"}]

Respond in language: ${language}. Return ONLY the JSON array, nothing else.`,
          topic: topicInput,
          level: "professional",
          history: [],
        }),
      });
      const data = await res.json();
      const raw = data.reply as string;
      const match = raw.match(/\[[\s\S]*\]/);
      if (match) {
        const parsed = JSON.parse(match[0]);
        setSlides(parsed);
        setCurrentSlide(0);
        setPreviewMode(true);
      }
    } catch {
      alert("Generation failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPPTX = async () => {
    if (slides.length === 0) return;
    const pptxgen = (await import("pptxgenjs")).default;
    const prs = new pptxgen();

    // Title slide
    const titleSlide = prs.addSlide();
    titleSlide.background = { color: "1e1b4b" };
    titleSlide.addText(topicInput, {
      x: 0.5, y: 1.5, w: 9, h: 1.5,
      fontSize: 36, bold: true, color: "ffffff",
      align: "center",
    });
    titleSlide.addText("Generated by EduSwarm 🚀", {
      x: 0.5, y: 3.5, w: 9, h: 0.5,
      fontSize: 14, color: "a5b4fc", align: "center",
    });

    // Content slides
    slides.forEach((slide) => {
      const s = prs.addSlide();
      s.background = { color: "0f172a" };

      // Title bar
      s.addShape(prs.ShapeType.rect, {
        x: 0, y: 0, w: 10, h: 1.2,
        fill: { color: "4f46e5" },
      });
      s.addText(`${slide.emoji} ${slide.title}`, {
        x: 0.3, y: 0.1, w: 9.4, h: 1,
        fontSize: 22, bold: true, color: "ffffff",
      });

      // Bullets
      slide.bullets.forEach((bullet, i) => {
        s.addShape(prs.ShapeType.rect, {
          x: 0.5, y: 1.5 + i * 0.85, w: 9, h: 0.7,
          fill: { color: i % 2 === 0 ? "1e293b" : "0f172a" },
          line: { color: "334155", width: 1 },
          rectRadius: 0.08,
        });
        s.addText(`• ${bullet}`, {
          x: 0.7, y: 1.55 + i * 0.85, w: 8.6, h: 0.6,
          fontSize: 14, color: "e2e8f0",
        });
      });
    });

    await prs.writeFile({ fileName: `${topicInput.replace(/\s+/g, "_")}_presentation.pptx` });
  };

  const updateSlide = (idx: number, field: keyof Slide, value: string | string[]) => {
    setSlides((prev) => prev.map((s, i) => i === idx ? { ...s, [field]: value } : s));
  };

  const addSlide = () => {
    setSlides((prev) => [...prev, { title: "New Slide", bullets: ["Point 1", "Point 2", "Point 3"], emoji: "📌" }]);
    setCurrentSlide(slides.length);
  };

  const removeSlide = (idx: number) => {
    setSlides((prev) => prev.filter((_, i) => i !== idx));
    setCurrentSlide((c) => Math.max(0, c - 1));
  };

  return (
    <div className="space-y-4">
      {/* Topic input */}
      <div className="space-y-2">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Topic</label>
        <input
          value={topicInput}
          onChange={(e) => setTopicInput(e.target.value)}
          placeholder="e.g. Machine Learning Basics"
          className="w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30"
        />
      </div>

      {/* Slide count */}
      <div className="space-y-2">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Number of slides: {slideCount}
        </label>
        <input type="range" min={3} max={12} value={slideCount}
          onChange={(e) => setSlideCount(Number(e.target.value))}
          className="w-full accent-primary"
        />
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>3</span><span>12</span>
        </div>
      </div>

      {/* Generate button */}
      <Button onClick={generateSlides} disabled={loading || !topicInput.trim()} className="w-full gap-2">
        {loading ? <><Loader2 className="h-4 w-4 animate-spin" />Generating slides…</> : <><Sparkles className="h-4 w-4" />Generate Slides</>}
      </Button>

      {/* Slide preview */}
      <AnimatePresence>
        {previewMode && slides.length > 0 && (
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="space-y-3">

            {/* Slide visual preview */}
            <div className="rounded-xl overflow-hidden border" style={{ background: "#0f172a", minHeight: 200 }}>
              <div className="px-4 py-2.5" style={{ background: "#4f46e5" }}>
                <p className="text-white font-bold text-base">
                  {slides[currentSlide]?.emoji} {slides[currentSlide]?.title}
                </p>
              </div>
              <div className="p-4 space-y-2">
                {slides[currentSlide]?.bullets.map((b, i) => (
                  <div key={i} className="flex items-start gap-2 rounded-lg px-3 py-1.5" style={{ background: i % 2 === 0 ? "#1e293b" : "#0f172a", border: "1px solid #334155" }}>
                    <span className="text-indigo-400 mt-0.5">•</span>
                    <span className="text-sm text-slate-200">{b}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between">
              <Button variant="outline" size="icon" onClick={() => setCurrentSlide((c) => Math.max(0, c - 1))} disabled={currentSlide === 0}>
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-xs text-muted-foreground font-medium">Slide {currentSlide + 1} / {slides.length}</span>
              <Button variant="outline" size="icon" onClick={() => setCurrentSlide((c) => Math.min(slides.length - 1, c + 1))} disabled={currentSlide === slides.length - 1}>
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>

            {/* Edit current slide */}
            <div className="rounded-xl border bg-muted/30 p-3 space-y-2">
              <p className="text-xs font-semibold text-muted-foreground">Edit Slide {currentSlide + 1}</p>
              <input value={slides[currentSlide]?.title ?? ""} onChange={(e) => updateSlide(currentSlide, "title", e.target.value)}
                className="w-full rounded-lg border bg-background px-3 py-1.5 text-sm outline-none focus:ring-2 focus:ring-primary/30"
                placeholder="Slide title"
              />
              {slides[currentSlide]?.bullets.map((b, bi) => (
                <input key={bi} value={b}
                  onChange={(e) => {
                    const updated = [...slides[currentSlide].bullets];
                    updated[bi] = e.target.value;
                    updateSlide(currentSlide, "bullets", updated);
                  }}
                  className="w-full rounded-lg border bg-background px-3 py-1.5 text-sm outline-none focus:ring-2 focus:ring-primary/30"
                  placeholder={`Bullet ${bi + 1}`}
                />
              ))}
            </div>

            {/* Actions */}
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={addSlide} className="gap-1.5 flex-1">
                <Plus className="h-3.5 w-3.5" /> Add Slide
              </Button>
              <Button variant="outline" size="sm" onClick={() => removeSlide(currentSlide)} className="gap-1.5 text-destructive hover:text-destructive flex-1">
                <Trash2 className="h-3.5 w-3.5" /> Remove
              </Button>
            </div>

            <Button onClick={downloadPPTX} className="w-full gap-2 bg-orange-500 hover:bg-orange-600 text-white">
              <Download className="h-4 w-4" /> Download .pptx ({slides.length} slides)
            </Button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
